extends: default

rules:
  braces:
    min-spaces-inside: 1
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0
  brackets:
    min-spaces-inside: 1
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0
  comments:
    min-spaces-from-content: 1
  document-end:
    present: false
  document-start: disable
  empty-lines:
    max: 1
  empty-values: enable
  indentation:
    spaces: 2
  hyphens:
    max-spaces-after: 2
  line-length:
    max: 100
  octal-values: enable
  quoted-strings:
    quote-type: single
    required: only-when-needed
