name: "Run JMH benchmarks"

on: # yamllint disable-line rule:truthy
  push:
    paths-ignore:
      - "README.md"

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
      - name: "Set up JDK 21"
        uses: "actions/setup-java@v4"
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "maven"
      - name: "Build with Maven"
        run: "./mvnw clean install"
      - name: "Run JMH benchmarks"
        run: "java -jar target/benchmarks.jar"
