# yamllint disable-line rule:truthy
on: push

jobs:
  lint:
    runs-on: ''
    steps:
      - uses: actions/checkout@v4
      - name: Install yamllint
        run: pip install yamllint
      - name: Lint YAML files
        run: yamllint .
